# Generated by Django 3.1.5 on 2021-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
