# Generated by Django 3.1.3 on 2021-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='invite',
            field=models.CharField(default='ZUG1NT', max_length=6),
        ),
    ]
