# Generated by Django 3.1.3 on 2021-02-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='invite',
            field=models.CharField(default='0313RY', max_length=6),
        ),
    ]
