# Generated by Django 3.1.3 on 2021-02-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210131_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
    ]
