# Generated by Django 3.1.3 on 2021-02-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210131_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=15),
        ),
    ]
