# Generated by Django 3.1.3 on 2021-02-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210204_0431'),
        ('main_app', '0002_club_invite'),
    ]

    operations = [
    ]
