# Generated by Django 3.1.3 on 2021-02-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210201_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
    ]
