# Generated by Django 3.1.3 on 2021-02-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210201_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='book',
        ),
    ]
