# Generated by Django 3.1.3 on 2021-02-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20210204_1627'),
        ('main_app', '0003_auto_20210203_1245'),
    ]

    operations = [
    ]
