# Generated by Django 3.1.3 on 2021-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_meeting_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='book',
        ),
    ]
