# Generated by Django 3.1.3 on 2021-02-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20210204_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='invite',
            field=models.CharField(default='NB4HDT', max_length=6),
        ),
    ]
