# Generated by Django 3.1.3 on 2021-02-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_rating_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.club'),
            preserve_default=False,
        ),
    ]
