# Generated by Django 3.1.3 on 2021-02-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='comment',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='disc_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('quesiton', 'Discussion Question'), ('quote', 'Quote')], max_length=100),
        ),
    ]
